import { 
  ENDPOINTS, 
  URL_ESTUDIANTES, 
  URL_ESTUDIANTE,
  URL_CREAR_ESTUDIANTE, 
  URL_EDITAR_ESTUDIANTE,
  URL_ELIMINAR_ESTUDIANTE,
  URL_CURSOS, 
  URL_CURSO,
  URL_CREAR_CURSO,
  URL_EDITAR_CURSO,
  URL_ELIMINAR_CURSO,
  URL_INSCRIPCIONES,
  URL_INSCRIPCIONES_ESTUDIANTE,
  URL_ACTUALIZAR_INSCRIPCIONES
} from '../endpoints/endpoints';

// Configuraciones de la aplicación
export const API_CONFIG = {
  BASE_URL: ENDPOINTS,
  ENDPOINTS: {
    ESTUDIANTES: URL_ESTUDIANTES,
    ESTUDIANTE: URL_ESTUDIANTE,
    CREAR_ESTUDIANTE: URL_CREAR_ESTUDIANTE,
    EDITAR_ESTUDIANTE: URL_EDITAR_ESTUDIANTE,
    ELIMINAR_ESTUDIANTE: URL_ELIMINAR_ESTUDIANTE,
    CURSOS: URL_CURSOS,
    CURSO: URL_CURSO,
    CREAR_CURSO: URL_CREAR_CURSO,
    EDITAR_CURSO: URL_EDITAR_CURSO,
    ELIMINAR_CURSO: URL_ELIMINAR_CURSO,
    INSCRIPCIONES: URL_INSCRIPCIONES,
    INSCRIPCIONES_ESTUDIANTE: URL_INSCRIPCIONES_ESTUDIANTE,
    ACTUALIZAR_INSCRIPCIONES: URL_ACTUALIZAR_INSCRIPCIONES
  }
};